version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/golang
    environment:
      - DEP_VERSION: 0.5.0
      - IMAGE_NAME: pullanusbot
      - TAG: 0.1.{{ .BuildNum }}
    working_directory: /go/src/github.com/ailinykh/pullanusbot

jobs:
  - setup:
    executor: my-executor
    steps:
      - checkout
      - run:
          command: |
            if [ ! -d vendor ]; then
              curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o /go/bin/dep
              chmod +x /go/bin/dep
              /go/bin/dep ensure
            fi

  - test:
    executor: my-executor
    requires:
      - setup
    steps:
      run:  
        command: go test -race -v -coverprofile=coverage.txt -covermode=atomic

  - coverage:
    executor: my-executor
    requires:
      - test
    steps:
      run:
        command: bash <(curl -s https://codecov.io/bash)

  - build:
    executor: my-executor
    requires:
      - test
    branches:
      only:
        - master
    steps:
      - run:
        command: |
          docker build -t ailinykh/$IMAGE_NAME:$TAG .
          echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
          docker push ailinykh/$IMAGE_NAME:$TAG
      - save_cache:
        key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
        paths:
          - vendor
    
  - deploy:
    executor: my-executor
    requires:
      - build
    steps:
      - run:
        name: Deploy app to Digital Ocean Server via Docker
        command: ssh -o StrictHostKeyChecking=no root@proxy.ailinykh.com "/bin/bash ./pullanusbot/deploy_app.sh $TAG"