version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/ailinykh/pullanusbot
    steps:
      - checkout
      - run: go get -u gopkg.in/tucnak/telebot.v2
      - run:
          name: run tests
          command: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./faggot
      - run: bash <(curl -s https://codecov.io/bash)