version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/ailinykh/pullanusbot
    steps:
      - checkout
      - run:
          name: run tests
          command: go test -race -v ./faggot