name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .
  
    - name: Test
      run: go test -race -v -coverprofile=coverage.txt -covermode=atomic
      
    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)


    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}

    - name: Setup tag
      run: TAG=0.2.$BUILD_NUMBER && echo $TAG
    
    - name: Build docker container
      run: |
        docker build -tag ${{ github.repository }}:$TAG
        echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
        docker push ${{ github.repository }}:$TAG
      env:
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

    - name: Deploy app
      run: echo "$SSH_IDENTITY_KEY" > identity && ssh -i identity -o StrictHostKeyChecking=no root@proxy.ailinykh.com "/bin/bash ./pullanusbot/deploy_app.sh $TAG"
      env:
        SSH_IDENTITY_KEY: ${{ secrets.SSH_IDENTITY_KEY }}
    
